export const IDUKKI_DATA = [
    { name: 'Devikulam', panchayatList: [
        { panchayat: ['Adimaly',21] },
        { panchayat: ['Bison Valley',13] },
        { panchayat: ['Chinnakanal',13] },
        { panchayat: ['Devikulam',18] },
        { panchayat: ['Edamalakudy',13] },
        { panchayat: ['Kanthalloor',13] },
        { panchayat: ['Mankulam',13] },
        { panchayat: ['Marayoor',13] },
        { panchayat: ['Munnar',21] },
        { panchayat: ['Pallivasal',14] },
        { panchayat: ['Vellathooval',17] },
    ]},
    { name: 'Idukki', panchayatList: [
        { panchayat: ['Arakulam',15] },
        { panchayat: ['Idukki kanjikuzhy',18] },
        { panchayat: ['Kamakshy',15] },
        { panchayat: ['Kanchiyar',16] },
        { panchayat: ['Karinkunnam',13] },
        { panchayat: ['Konnathady',19] },
        { panchayat: ['Kudayathoor',13] },
        { panchayat: ['Mariyapuram',13] },
        { panchayat: ['Vathikudy',18] },
        { panchayat: ['Vattavada',13] },
        { panchayat: ['Vazhathopp',14] },
    ]},
    { name: 'Kothamangalam', panchayatList: [
        { panchayat: ['Kavalangad',18] },
        { panchayat: ['Keerambara',13] },
        { panchayat: ['Kottappadi',13] },
        { panchayat: ['Kuttambuzha',17] },
        { panchayat: ['Nellikuzhi',21] },
        { panchayat: ['Pallarimangalam',13] },
        { panchayat: ['Pindimana',13] },
        { panchayat: ['Varapetti',13] },
    ]},
    { name: 'Muvattupuzha', panchayatList: [
        { panchayat: ['Arakuzha',13] },
        { panchayat: ['Avoli',14] },
        { panchayat: ['Ayavana',14] },
        { panchayat: ['Kallorkadu',13] },
        { panchayat: ['Manjallor',13] },
        { panchayat: ['Marady',13] },
        { panchayat: ['Paingottur',13] },
        { panchayat: ['Palakuzha',13] },
        { panchayat: ['Payipra',22] },
        { panchayat: ['Pothanikkadu',13] },
        { panchayat: ['Valakom',14] },
    ]},
    { name: 'Peerumedu', panchayatList: [
        { panchayat: ['Ayyapankovil',13] },
        { panchayat: ['Chakkupallam',15] },
        { panchayat: ['Elappara',17] },
        { panchayat: ['Kokkayar',13] },
        { panchayat: ['Kumily',20] },
        { panchayat: ['Peerumedu',17] },
        { panchayat: ['Peruvanthanam',14] },
        { panchayat: ['Upputhara',18] },
        { panchayat: ['Vandiperiyar',23] },
    ]},
    { name: 'Thodupuzha', panchayatList: [
        { panchayat: ['Alakode',13] },
        { panchayat: ['Edavetty',13] },
        { panchayat: ['Karimanoor',14] },
        { panchayat: ['Kodikulam',13] },
        { panchayat: ['Kumaramangalam',13] },
        { panchayat: ['Manakkad',13] },
        { panchayat: ['Muttom',13] },
        { panchayat: ['Purapuzha',13] },
        { panchayat: ['Udumbannor',16] },
        { panchayat: ['Vannapuram',17] },
        { panchayat: ['Velliyamattam',15] },
    ]},
    { name: 'Udumbanchola', panchayatList: [
        { panchayat: ['Erattayar',14] },
        { panchayat: ['Karunapuram',17] },
        { panchayat: ['Nedumkandam',22] },
        { panchayat: ['Pambadumpara',16] },
        { panchayat: ['Rajakkad',13] },
        { panchayat: ['Rajakumary',13] },
        { panchayat: ['Santhanpara',13] },
        { panchayat: ['Senapathy',13] },
        { panchayat: ['Udumbanchola',14] },
        { panchayat: ['Vandanmedu',18] },
    ]},
]